### PR TITLE
feat: docker support

### LINKED ISSUE #22: [REQ] Docker Support
# Overview
Self-explanatory. Re-add proper dockerfiles that don't throw a bloody fit. I'm not very good with devops. Also, we have a docker util file to detect if we're running in docker.

# Notes
Use the default port values in config.json for rethinkdb/dash/firewall/etc. User can edit them if they want to. PM2 is great and does it's job but TTtie made fun of me :'( 

Also sorry for assigning you to so much stuff

### PR DESCRIPTION
**Pull request by TTtie**
## What does this PR do?
- [x] Adds a feature
- [ ] Fixes a bug
- [ ] Edits documentation
- [ ] Edits this repository
- [ ] Something else

## Things to check
- [x] Have you tested changes locally?
- [x] Have you followed our linter rules?

## Notes
- [ ] New dependencies added
- [x] Unsure of functionality

## Description
Adds support for Docker.

### CODE REVIEW

**Comment by espimarisa** [comment]
You told me not to merge this yet, so I'll wait for you to do proper tests etc.

**Comment by espimarisa** [comment]
Also, we need to account for initial rethinkdb setup. Either by hooking it into the bot or running "npm run setup"

**Comment by TTtie** [comment]
I'll try to account for that - the reason why we're not merging yet is that I haven't implemented `db.wait()` which waits for the databases to come up; I already received a few errors in production because of this.

**Comment by espimarisa** [comment]
Sounds good, I completely forgot about .wait()

**Comment by TTtie** [comment]
@smolespi This should be ready for review now.

**Comment by espimarisa** [comment]
I had trouble getting it to function under WSL but Docker on Windows + WSL is finicky. Works on proper Linux systems (@TTtie demonstrated) so I'll merge it.

**Pull request merged**
