### PR TITLE
[WIP] new Fastify-based webserver with React frontend

### PR DESCRIPTION
**Pull request by VottusCode**
# :warning: WIP - don't merge

## What does this PR do?

- [x] Adds or edits a feature
- [ ] Fixes a bug
- [ ] Edits typings
- [ ] Edits documentation
- [ ] Edits config files
- [ ] Edits CI or workflows
- [x] Something else

## Things to check

- [ ] Have you tested changes locally?
- [ ] Have you followed our linter rules?
- [ ] Have you ensured TypeScript compiles?

## Notes

- [x] New dependencies added
- [x] Unsure of functionality

## Description

New website. I started working on it in my repo, now its a submodule, later to be merged completely. Now some backend stuff needs to be done, hence why i'm openning this PR. It's WIP, don't merge.

The temp frontend repo (linked as a submodule): https://github.com/VottusCode/hibiki-indev - latest changes are in the dashboard branch.

## TODO
[ ] Fix CSP

### CODE REVIEW

**Comment by VottusCode** [comment]
this is pain because you use RethinkDBStore for sessions which is supported by fastify-session but not fastify-secure-session which is required by fastify-passport. It's making me desperate because idk where to go next.

**Comment by espimarisa** [comment]
Actually, I own session-rethinkdb-ts https://github.com/sysdotini/session-rethinkdb-ts

Realistically it shouldn't take *too* much modification to get it to work with fastify.

**Comment by VottusCode** [comment]
> 
> 
> Actually, I own session-rethinkdb-ts https://github.com/sysdotini/session-rethinkdb-ts
> 
> Realistically it shouldn't take _too_ much modification to get it to work with fastify.

i know you do, you told me some time ago, the problem isn't the library, the problem is in fastify-secure-session not having custom stores but being required by fastify-passport, while fastify-session is an alternative that does support stores but isn't supported by fastify-passport.

**Comment by espimarisa** [comment]
Oh I'm fucking blind.

The main problem I've had with Fastify is shitty oauth and awful session libs. It's always *something*.
If we need to use a different type of store we can.

**Comment by VottusCode** [comment]
> 
> 
> Oh I'm fucking blind.
> 
> The main problem I've had with Fastify is shitty oauth and awful session libs. It's always _something_.
> If we need to use a different type of store we can.

Alr. I'll take a look at it tomorrow.

**Comment by VottusCode** [comment]
Sessions are finally settled once and for all, using fastify-secure-session to retain the user ID, then rest of the data is cached in Redis.

**Comment by lambdagg** [comment]
hi, asking for news! lmk when you're working again on this. lambdagg#4887

**Comment by VottusCode** [comment]
> hi, asking for news! lmk when you're working again on this. lambdagg#4887

i haven't worked on this for a while because I wanted to spend some time off irl, but I'll start working on it soon.

**Comment by lambdagg** [comment]
> i haven't worked on this for a while because I wanted to spend some time off irl, but I'll start working on it soon.

no problem. I'll be waiting :)

**Comment by VottusCode** [comment]
Okay I'm back and I'll finally do some more work.

**Comment by espimarisa** [comment]
I think that it's safe to say that this project is stuck in dev-hell. I am closing this PR as the future of Hibiki is currently unknown due to Discord's API changes coming in April 2022.

**Comment by VottusCode** [comment]
Yeah, I kinda didn't want to work on any discord bot-related stuff because of the said changes to the API, it's kinda weird and it can tear apart discord bots altogether.

**Pull request closed without merging**
